### PR TITLE
feat: add docs on farming policies

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

**Comment by mohamedamer453** [comment]
### Doc changes

-  in line 7 where is the id field ?

-  in line 10 ipv4 should be mentioned with the su,cu, and nu.

- There's a conflict in the docs in line 11 it says that the minimalUptime field can be decimal and in line 51 it says that it should be expressed as integer. (Line 51 is the correct one. You can't even type a "." In this field)

- in line 12, it should be renamed to `policy end` instead of `policy end date` since the field accepts a BlockNumber not a date.

### Issues 

- on [testnet](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.test.grid.tf#/council/motions) after filling the data exactly as seen in the docs screenshot the `Propose` button was disabled and i couldn't add a proposal.

   image

- also as seen in the screenshot above i noticed that the last 2 fields (`nodeCertification`, `farmCertification`) on testnet are different and they don't have a dropdown with the different options like the screenshot in the docs and on qanet

- also when i selected the `createFarmingPolicy` action at first i noticed that some errors appear in the console related to these 2 fields.

   image

- I tried to change the inputs multiple times and tried to use other node/farm certifications but the button was disabled for all the options i tried.

*** note: all the issues mentioned above are on [testnet](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.qa.grid.tf#/council/motions). i tried the same config on qa net and the button was not disabled and the last 2 fields had dropdown menus with certification options as seen in the docs screenshot.

**Comment by DylanVerstraete** [comment]
> * in line 7 where is the id field ?

The `id` is generated.


On testnet you still need the [types](https://raw.githubusercontent.com/threefoldtech/tfchain_client_js/master/types.json) in order to submit a proposal

**Comment by mohamedamer453** [comment]
> On testnet you still need the [types](https://raw.githubusercontent.com/threefoldtech/tfchain_client_js/master/types.json) in order to submit a proposal

So what exactly should the input in these 2 fields look like cuz i'm not familiar with these types and i tried different inputs  like `NodeCertification` and `FarmCertification`. 

and i also tried these certification types from the json file you mentioned

image

and i was still not able to submit a proposal.

**Comment by DylanVerstraete** [comment]
@mohamedamer453 are you sure you are a member of the council?

**Pull request merged**
